###########kafka配置###########
# 指定kafka 代理地址，可以多个
spring.kafka.bootstrap-servers: 192.168.88.177:9092
# 指定默认消费者group id
spring.kafka.consumer.group-id: jonGroup
# 指定默认topic id
spring.kafka.template.default-topic: jon-replicated-topic
# 指定listener 容器中的线程数，用于提高并发量
spring.kafka.listener.concurrency: 3
# 每次批量发送消息的数量
spring.kafka.producer.batch-size: 1000



server.port: 9000

#kafka.broker-address: 10.12.28.195:9092,10.12.28.211:9092,10.12.28.215:9092
kafka.broker-address: 192.168.50.111:9092,192.168.50.112:9092,192.168.50.113:9092

kafka.groupId: default